### PR TITLE
AA/kbs_protocol: fix RCAR handshake protocol

### LINKED ISSUE #366: kbs_protocol does not follow the KBS spec
In the KBS spec, it says "The hash of the `tee-pubkey` field must be included in the custom field of HW-TEE evidence and signed by HW-TEE hardware."

kbs_protocol hashes only parts of `tee-pubkey`
https://github.com/confidential-containers/guest-components/blob/914251abcb4b8c5a06acf126df5d71cf50451bd2/attestation-agent/kbs_protocol/src/client/rcar_client.rs#L93

### PR DESCRIPTION
**Pull request by Xynnn007**
Before this commit, the tee-pubkey is not fully integrity-protected by binding the digest into the evidence. The update of this commit is aligned with the KBS side.

Fixes #366

cc @mythi

### CODE REVIEW

**Comment by Xynnn007** [comment]
The test failure is as expected because the runtime data changes.

File: attestation-agent/kbs_protocol/src/client/rcar_client.rs [hunk 1]
```diff
@@ -133,8 +134,13 @@ impl KbsClient<Box<dyn EvidenceProvider>> {
 
         debug!("get challenge: {challenge:#?}");
         let tee_pubkey = self.tee_key.export_pubkey()?;
-        let materials = vec![tee_pubkey.k_mod.as_bytes(), tee_pubkey.k_exp.as_bytes()];
-        let evidence = self.generate_evidence(challenge.nonce, materials).await?;
+        let runtime_data = json!({
+            "tee-pubkey": tee_pubkey,
+            "nonce": challenge.nonce,
+        });
```
Comment (mythi) [inline attestation-agent/kbs_protocol/src/client/rcar_client.rs:140]: is there a reason why to combine them? My expectation was to have it the same way it's implemented in #369

Comment (Xynnn007) [reply attestation-agent/kbs_protocol/src/client/rcar_client.rs:140]: no matter Nonce or tee pub key, they all are things whose integrity should be protected by binding the evidence. There must be more scenarios except for the two fields.

We use a json map here to have a standard way to organize them

Comment (mythi) [reply attestation-agent/kbs_protocol/src/client/rcar_client.rs:140]: this contributes to the hashing problem we've talked about. it's not only what hash algorithm is used but also what data is hashed. this won't work well with Intel Trust Authority which makes me think that perhaps we are going to need AS specific cfg flags to decide how the reportdata needs to be generated by the attesters

Comment (Xynnn007) [reply attestation-agent/kbs_protocol/src/client/rcar_client.rs:140]: see the runtime data spec https://github.com/confidential-containers/kbs/issues/259

This would be a good start to make runtime data usage more standard

Comment (mythi) [reply attestation-agent/kbs_protocol/src/client/rcar_client.rs:140]: thanks! I saw it earlier but forgot to take a closer look. I'll do it today.

**Review by fitzthum — APPROVED** [review]
LGTM. This seems closely tied to https://github.com/confidential-containers/kbs/issues/259 but I guess we can implement that separately.

**Comment by Xynnn007** [comment]
cc @mythi Is this PR now good to you?

**Review by mythi — APPROVED** [review]
+1
